### PR TITLE
Camel addon to forge

### PR DESCRIPTION
**Pull request by oscerd**
Hi,

This PR is related to https://github.com/fabric8io/fabric8/issues/4186

I've rebased from forge website-data and I've added camel-addon block inside addons-community.yaml.

When the PR will be merged, you can submit a PR to the original forge website-data :-)

Maybe we can think to add to the site a Kubernetes-addon too.

Andrea

### CODE REVIEW

**Comment by jimmidyson** [comment]
Thanks @oscerd! Do you want to submit the PR to the original forge website data?

Good idea about the kubernetes add-on BTW.

**Comment by oscerd** [comment]
Yes Jimmi. I'll submit the PR now :-)

**Comment by oscerd** [comment]
Done :-)

https://github.com/forge/website-data/pull/14

**Comment by jimmidyson** [comment]
Thanks!

**Pull request merged**
